# Generated by Django 5.0.4 on 2024-04-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0005_alter_teammember_email_alter_teammember_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
